DELIMITER ;;

DROP FUNCTION IF EXISTS UUID_TO_BIN;;

CREATE FUNCTION UUID_TO_BIN(
  p_uuid VARCHAR(36)
)
  RETURNS BINARY(16) DETERMINISTIC
  COMMENT 'VARCHAR 형태의 UUID를 BINARY 형태로 변환'
BEGIN
  DECLARE v_bin BINARY(16);

  SET v_bin = UNHEX(REPLACE(p_uuid, '-', ''));

  RETURN v_bin;
END;;

DELIMITER ;
